apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kevin-helloworld-app-placement
  labels:
    app: kevin-helloworld-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
