apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: kevin-helloworld-app-subscription
  labels:
    app: kevin-helloworld-app
  annotations:
    apps.open-cluster-management.io/github-path: helloworld
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: kevin-multilevel-channel/kevin-multilevel-channel
  placement:
    placementRef:
      name: kevin-helloworld-app-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
