apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kevin-multilevel-app-placement
  namespace: kevin-multilevel-app
  labels:
    app: kevin-multilevel-app
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
