apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kevin-managedcluster
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kevin-managedcluster
