apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: kevin-managedcluster
  namespace: kevin-managedcluster
  labels:
    app: kevin-managedcluster
spec:
  clusterReplicas: 1
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
