apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: multisub
spec:
  clusterSelector:
    matchLabels:
      environment: Dev
  clusterReplicas: 1
