apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: multisub-a
  namespace: multisub
  labels:
    multisub: True
  annotations:
    apps.open-cluster-management.io/git-path: multisub-a
    apps.open-cluster-management.io/git-branch: master

spec:
  channel: multisub-ch/multisub
  placement:
    placementRef:
      name: towhichcluster
      kind: PlacementRule
